sonar.sources=api-auth
sonar.tests=api-auth/test

sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=api-auth/coverage.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.venv/**,**/venv/**,**/.pytest_cache/**,security/evidence/**

sonar.test.inclusions=api-auth/test/**/*.py